apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    argocd/app-selector: rht-gitops.com/janus-argocd=quarkus-app-bootstrap
  name: test-application
  description: An example of a Backstage application.
spec:
  type: service
  owner: janus-authors
  lifecycle: unknown